### PR TITLE
Add note that version must be statically set

### PR DESCRIPTION
**Pull request by justinedelson**

### CODE REVIEW

**Comment by justinedelson** [comment]
@jyotikas same as https://github.com/AdobeDocs/experience-manager-cloud-service.en/pull/111

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for this, @justinedelson.

CQDOC-17959

**Comment by guillaumecarlino** [comment]
Closing as not was published.

**Pull request closed without merging**
