### PR TITLE
Add note about when and how to use custom maven repositories

### PR DESCRIPTION
**Pull request by cziegeler**
Custom maven repos should only be used for code not tied to AEM and source/project sources should be deployed alongside

### CODE REVIEW

**Comment by cziegeler** [comment]
@justinedelson @jyotikas Please review

**Comment by justinedelson** [comment]
This looks good to me. This same change should also be made on the cloud service version of this page.

**Comment by cziegeler** [comment]
@justinedelson Can you please point me to that doc? I can prepare a PR for it as well

**Comment by justinedelson** [comment]
@cziegeler https://github.com/AdobeDocs/experience-manager-cloud-service.en/blob/master/help/onboarding/getting-access-to-aem-in-cloud/creating-aem-application-project.md

**Comment by jyotikas** [comment]
Thank you @cziegeler for reporting.
Both the Guides reflect the updates:
1. https://docs.adobe.com/content/help/en/experience-manager-cloud-service/onboarding/getting-access/creating-aem-application-project.html#password-protected-maven-repositories
2. https://docs.adobe.com/content/help/en/experience-manager-cloud-manager/using/getting-started/create-an-application-project.html#password-protected-maven-repositories

**Comment by bohnertchris** [comment]
Tracked in CQDOC-16864

**Comment by guillaumecarlino** [comment]
Closing as this was fixed.

**Pull request closed without merging**
